### ISSUE TITLE
fetching torrent metadata from 2 peers

### ISSUE THREAD

**Issue by slrslr** [feross/webtorrent-cli#10]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
webtorrent-cli 1.2.3, webtorrent 0.95.2

**What operating system and version?**
CentOS 6.x

**What did you do?**
Linux command: webtorrent download "magnetlinkhere" --verbose

**What did you expect to happen?**
Download complete

**What actually happened?**
it just print: fetching torrent metadata from 2 peers
and nothing

Is there any log or more verbosity? I see no log path when i do command: webtorrent --help and cant find nothing in /var/log

**Comment by DiegoRBaquero** [comment]
can you set DEBUG env bar to * and post the full logs?

Most probably you can't connect to those 2 peers because of firewalls or network config on either you or them.

**Comment by slrslr** [comment]
thx, im not a programmer, so im unsure where i can set "DEBUG env bar to *".
But i also think its a network issue. Seeding worked from the Linux server to my Windows 10 home computer, but not vice versa.

**Comment by feross** [comment]
This makes sense -- WebTorrent needs to do better NAT hole punching. https://github.com/feross/webtorrent/issues/195

What @DiegoRBaquero meant about DEBUG is that you can get detailed debug logs by starting `webtorrent-cli` like this:

```
DEBUG=* webtorrent "magnet_link"
```

**Comment by slrslr** [comment]
One year passed, i see that i still have this issue. On the Windows computer where i am seeding the torrent via Webtorrent.desktop, i am using OpenVPN to connect internet and i am blocking non VPN traffic.

This is what i see on that computer (Windows seeder):
![sdsdd](https://s20.postimg.org/6kswo2zt9/webtorrent-openvpn-connections.gif)

And it seems i can not download from this computer, because when i executed the DEBUG command mentioned by feross (thank you) on my remote Linux server (has different IP&location from my VPN server and my Windows computer), it shows detailed output and among others this:
  webtorrent:peer destroy myVpnIpHere:61095 (error: connect E**CONNREFUSED** MyVpnIpHere:61095) +50ms

What is the meaning of this please? Either VPN or my Windows computer refused connection. I do not think it is VPN because VPN works good for other apps like other bittorrent client, web browser. So it have to be WIndows computer, but I allowed WebTorrent inside my Comodo firewall once it asked and per the screenshot above, the webtorrent is listening i believe. Is webtorrent.desktop doing all connections via VPN? I have WebRTC disabled in my default web browser (Firefox) and i want it that way because i listen IP can leak thru it when using VPN. Thank You in advance for the feedback.
