### ISSUE TITLE
Auto-close webtorrent-cli when player exits

### ISSUE THREAD

**Issue by iovis9** [feross/webtorrent-cli#14]
Would this be interesting? I don't have any use to keep it downloading after I'm finished and I wouldn't mind doing a PR.

**Comment by feross** [comment]
Sure -- PR welcome.

**Comment by feross** [comment]
@iovis9, thanks for the recent PRs. I've added you as a maintainer of this repo. Please read the [contributing guidelines](https://github.com/feross/webtorrent-cli/blob/master/CONTRIBUTING.md).

Cheers! 👍

**Comment by iovis9** [comment]
Thanks, I appreciate it :)
