### ISSUE TITLE
DLNA Support

### ISSUE THREAD

**Issue by iovis9** [feross/webtorrent-cli#16]
I made some advances on DLNA streaming on my own a while ago and I even use it in a fork I did from [peerflix](https://github.com/iovis9/peerflix) for my content discovery tool, [peerflixrb](https://github.com/iovis9/peerflixrb). The idea is easier to follow in a little script I made called [dlnast](https://github.com/iovis9/dlnast/blob/master/index.js).

Disclaimer: I'm probably a terrible node developer and I have a very little understanding of DLNA, expect weird things.

The gist of it would be reusing the server to serve the content and subtitles and use something like  [nodecast-js](https://github.com/gyzerok/nodecast-js) and [upnp-mediarenderer-client](https://github.com/thibauts/node-upnp-mediarenderer-client) to discover clients and send them the content.

It works for LG TVs, at least the two I tested it with. Can't say anything about other brands nor what happens when there's more than one smart TV.

Thoughts?

**Comment by feross** [comment]
Not a bad idea. But I prefer that we use the same DLNA module that WebTorrent Desktop already uses so we can keep things consistent.

The module is https://www.npmjs.com/package/dlnacasts, by @grunjol.

**Comment by iovis9** [comment]
I'll look into it!

**Comment by grunjol** [comment]
You can check how we implemented it in WTD [cast.js ](https://github.com/feross/webtorrent-desktop/blob/master/src/renderer/lib/cast.js). We wrapped dlna, airplay and chromecast under the same interface.

**Comment by iovis9** [comment]
Yeah, actually I already found the PR and everything, but thanks for the feedback!

**Comment by iovis9** [comment]
How do you propose (interface-wise) that we solve this?
https://github.com/feross/webtorrent-desktop/pull/573

**Comment by grunjol** [comment]
The same applies to the other casting devices. Right now, it casts to the first available device

**Comment by iovis9** [comment]
When I tinkered with this on my own I streamed it to the first available too as I only had one, but I haven't used your tool yet so I didn't know how it handles this issue. When I saw that PR I thought it was related.

BTW, how is it supposed to work on WTD? I've seen no interface to send it to my TV.

**Comment by grunjol** [comment]
if you check [line 51](https://github.com/feross/webtorrent-desktop/blob/master/src/renderer/lib/cast.js#L51) you can see when a new device is detected its added to a list of available devices and is displayed on the UI with a TV icon.

![image](https://cloud.githubusercontent.com/assets/6145761/17609727/0cfc3e6c-600e-11e6-8092-a5130b158ec4.png)

In this case I have 3 DLNA devices at home which I can select.

**Comment by iovis9** [comment]
My TV randomly disconnected and that's why I couldn't see it. Everything working as expected!
