### ISSUE TITLE
Seed multiple files at once

### ISSUE THREAD

**Issue by elendirx** [feross/webtorrent-cli#20]
Hi, I'm using webtorrent-hybrid on a headless server to seed multiple files. I'm seeding each file in its own screen (as the CLI can only seed one file at a time) and with 5+ files I find myself constantly switching screens to control seeding of each file. It would be awesome if I could pass an array of files to the CLI as a param. Thanks a lot!

**Comment by elendirx** [comment]
Never mind, I solved all my troubles with the CLI by installing virtual display and webtorrent-desktop on the server. Please close this issue as bogus. Sorry.

**Comment by feross** [comment]
I think this is actually worth supporting. This was on my todo list, and I've been asked about it before too.

Here's a PR that implements support for downloading multiple torrents or seeding multiple files/folders at the same time: https://github.com/feross/webtorrent-cli/pull/21

**Comment by iovis9** [comment]
How does it handle media player streaming?

**Comment by feross** [comment]
> @iovis9 How does it handle media player streaming?

Not very well. Will consider how to improve the PR.

**Comment by feross** [comment]
@iovis9 I think it makes the most sense to just disallow certain command line options like player streaming when multiple torrents are specified. I can't imagine users wanting to stream two torrents into two instances of VLC very often. If they want that, they can just run `webtorrent` twice.

So, that's the solution. We'll print: `Error: The --vlc argument cannot be used with multiple files/folders.`

**Comment by omgbox** [comment]
@feross any plans for  seed collection agent ?

automatically feeds it to the collection agent that seeds the file.
> webtorrent seed add example.avi 

showing whats active seeding in the collection list. 
> webtorrent seed show active
------------------------------------------------------------
seed collection agent v1 [ 900 ] files seeded
------------------------------------------------------------
>[1]. ninja_dogs.mp4
Info hash: aa46d3ad319ddf109ae56caa97b98765986ae148
-----------------------------------------------------------
>[2]. ninja_cats.mp4
Info hash: aa98765677657809ae598765678766e986ae148
-----------------------------------------------------------

getting all the info hash 
> webtorrent export seed active > list.log

**Comment by feross** [comment]
@omgbox Not sure what you mean by "seed collection agent" but it sounds complicated.
