### ISSUE TITLE
RFE | add automatic --subtitles-search -S 

### ISSUE THREAD

**Issue by kim0** [feross/webtorrent-cli#22]
webtorrent-cli is pure awesomeness! It has mostly replaced popcorntime for me! One feature I'm sorely missing however, is searching online resources for subtitles automatically and using them. So ideally the behavior is:
• If a subtitles file is found inside the torrent, it should be used
• If not, an automatic search for subtitles will be done. Some tools claim to perform a fingerprint (hash) of the movie so that it accurately finds subtitles!
* If multiple subtitles are found, it would be awesome to flip through them via a hot-key (while playback is happening)

Thanks!

**Comment by feross** [comment]
Subtitles are a copyrighted work, unless the author has released them to the public domain, or under a Creative Commons license. I'm sorry, but such a feature cannot be added to WebTorrent.
