### ISSUE TITLE
verbose CLI references non-existent property 'numQueued'

### ISSUE THREAD

**Issue by allanlw** [feross/webtorrent-cli#25]
In verbose mode, the CLI references `numQueued` property which does not exist. This used to work, but broke with webtorrent version v0.97.2 (see [this commit](https://github.com/feross/webtorrent/commit/3daee2c66cbf752b9e6e49b99492b8c1914a4a58)), as the property was renamed to `_numQueued`.

Either this property should be referenced even though it's "private", or this section of the display should be removed. Happy to submit a PR either way, but seems more like a design decision with respect to package coupling, so decided to file a bug for discussion instead.

**Comment by allanlw** [comment]
Note that this results in the verbose line always starting with:

    Queued peers: undefined

**Comment by feross** [comment]
Thanks for the issue. Let's rename the variable so it works again. `--verbose` is mainly used by us developers to debug webtorrent, so it's fine if we're coupled.

**Comment by allanlw** [comment]
Sounds good to me. PR #28 submitted.
