### ISSUE TITLE
Playlist

### ISSUE THREAD

**Issue by matthewdias** [feross/webtorrent-cli#30]
Would it be possible to get playlist support for torrents with multiple video files?

**Comment by feross** [comment]
I would consider using [WebTorrent Desktop](https://webtorrent.io/desktop) instead of the CLI if you want playlist support. I would prefer to keep the CLI implementation straightforward.

**Comment by bas080** [comment]
It might be possible to use the m3u playlist format for cross video player support. The webtorrent would need support for requesting different files without the need for restarting the process.
