### ISSUE TITLE
Streaming to omx can't quit player

### ISSUE THREAD

**Issue by nkittsteiner** [feross/webtorrent-cli#7]
Using a raspberry pi 2 with raspbian jessie, I run webtorrent --omx=hdmi "some magnet link". The stream looks OK but I can't quit the application neither kill it because is in full screen mode.

**Comment by nkittsteiner** [comment]
Sorry, with Ctrl+C exit wt-cli

**Comment by iovis9** [comment]
If someone else gets here with Google: this is because omx needs to be called from a terminal that can read the keystrokes for its keybindings. This is solved calling omx like this `cmd = 'lxterminal -e ' + OMX_EXEC + ' ' + href`
